# दोन रिप्लिका राहू दे जेणेकरून हाय-अवेलेबिलिटी राहील
replicaCount: 2

image:
  repository: 588319086414.dkr.ecr.eu-north-1.amazonaws.com/shailesh-repo
  pullPolicy: IfNotPresent
  # हा टॅग आपण CI.yml मधून 'latest' सेट करतोय
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  # तुमचं Spring Boot ॲप 8080 वर चालतं, म्हणून targetPort 8080 असायला हवा
  targetPort: 8080

ingress:
  enabled: false

resources: {}

# Probes मुळे तुमचं ॲप हेल्दी आहे की नाही हे EKS ला समजतं
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 45 # ॲपला सुरू व्हायला थोडा जास्त वेळ देऊया
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 45
  periodSeconds: 10

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}