apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-container
          image: imandemo9999/my-bank-app
          ports:
            - containerPort: 8080