replicaCount: 1

image:
  repository: 588319086414.dkr.ecr.us-east-1.amazonaws.com/shailesh-new-ecr
  pullPolicy: Always # Always वापरणं चांगलं कारण आपण 'latest' टॅग वापरतोय
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# ✅ हेल्थ चेकसाठी ८०८० पोर्ट आणि ४५ सेकंदांचा डिले दिला आहे
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 45
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 45
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: false
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}