replicaCount: 1

image:
  repository: 588319086414.dkr.ecr.us-east-1.amazonaws.com/shailesh-new-ecr
  pullPolicy: IfNotPresent
  tag: "latest" # आपण पाईपलाईन मधून 'latest' पाठवतोय

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# ✅ हे प्रोब्स आता ८० ऐवजी थेट ८०८० पोर्ट चेक करतील
livenessProbe:
  httpGet:
    path: /
    port: 8080
readinessProbe:
  httpGet:
    path: /
    port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: false

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}